import {
  etchImg,
  knightImg,
  ledImg,
  mastermindImg,
  portalImg,
  portfolioImg,
} from "../assets";

export const projects = [
  {
    id: "portal",
    title: "E-Learning Portal",
    desc: "A new portal for 1000+ parents, teachers, TAs, and admins. I was hired to update an outdated UI/UX and implement new features like scheduling and internal messaging. This portal is what taught me React, full life-cycle development from start to production, and the confidence to come up with my own creative software solutions.",
    thumbnailImg: portalImg,
    skills: [
      "React.js",
      "TailwindCSS",
      "Docker",
      "RESTful API",
      "Axios",
      "Vite",
      "MathJax",
      "UI/UX",
      "QA Design",
    ],
  },
  {
    id: "portfolio",
    title: "My Portfolio",
    desc: "I had wanted to make a portfolio website for a while, and after going through the full life-cycle development of the Mr. Math Portal, I knew I had the skills to finally build it. I used this portfolio as an opportunity to learn TypeScript. The theme is inspired by a photo I took from a bridge in Chattanooga at sunset.",
    thumbnailImg: portfolioImg,
    skills: [
      "TypeScript",
      "React.js",
      "TailwindCSS",
      "Vite",
      "Vercel",
      "Framer Motion",
    ],
  },
  {
    id: "knight",
    title: "Knight Travails",
    desc: "Find the quickest path for a Knight chess piece to get from square A to square B. Created a graph with each possible move for a knight. With a Breadth First Search, the program stops at the first instance of the destination square, and reports the number of moves required, as well as the path taken.",
    thumbnailImg: knightImg,
    skills: ["Ruby", "Graph Theory", "BFS"],
  },
  {
    id: "etch",
    title: "Etch-A-Sketch",
    desc: "This is a fun web app I created when I was really trying to hone in on the basics of HTML/CSS/JS. I made the UI/UX as user-friendly as possible, which evidently lead to being hired to make the Mr. Math portal. There is an input for variable grid sizes, and buttons for different color selection. I even added a button that can change the opacity of the squares. This allows for some outside of the box sketches if you have the time!",
    thumbnailImg: etchImg,
    skills: ["JavaScript", "HTML", "CSS"],
  },
  {
    id: "mastermind",
    title: "Mastermind",
    desc: "Build the game of Mastermind. The computer utilizes Donald Knuth's solution to crack the code you create in 5 attempts or less every time. This solution involves a Minimax Algorithm. A tree is built and each possible outcome is assessed to pick a node that would eliminate the most possible options. I included Pruning to reduce the solve time by a few minutes.",
    thumbnailImg: mastermindImg,
    skills: ["Ruby", "Trees", "Minimax Algorithm", "Pruning"],
  },
  {
    id: "lights",
    title: "Arduino LED's",
    desc: "An LED strip programmed with an Arduino glows in various patterns. I was inspired by my own LED light strip I had in my dorm. I thought it would be fun to have my own custom patterns for it. The light strip had 4 wires. Red, Blue, Green, and Ground. Giving power to these different values let me adjust the colors for each LED. My favorite pattern mimicked twinkling snow for the winter time.",
    thumbnailImg: ledImg,
    skills: ["Arduino Programming"],
  },
];
